spring.application.name=Stockoholic
#api.key=5Tr1INvldsBcE0JLcMMhqESYXWcXiq9a

api.key2=fPoDzQ7JiRMiDbEQtSY0rKBngPafCjVi

api.key3=6kqvK5mQEpVRXt1ve1Mz6QcKkg44FE6j

api.news.url=https://api.apilayer.com/financelayer/news